### PR TITLE
API changes due to signal-details change in gir

### PR DESCRIPTION
**Pull request by zec**
This updates the `gir` submodule to the current `master` and regenerates the generated code, much like in gtk-rs/gtk-rs#324.

### CODE REVIEW

**Comment by zec** [comment]
Let me fix that CI failure and rebase...

**Comment by zec** [comment]
Hmm, that failed too... Looks like the `cargo fmt` in the `gir-sys` Makefile target doesn't actually format `webkit2gtk-sys/`.

Let me fix that, then try again.

**Comment by zec** [comment]
_There_ we go!

**Comment by zec** [comment]
Incidentally, this PR fixes issue #31.

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by zec** [comment]
Is there anything blocking this being merged?

**Comment by antoyo** [comment]
Thanks!

**Comment by zec** [comment]
I'll take that to mean no. :)

Thanks to everyone for reviewing this.

**Pull request merged**
