### PR TITLE
Regenerate bindings and sys

### PR DESCRIPTION
**Pull request by matzipan**
Hi,

This PR regenerates with latest gir and gir-files.

However, it's currently not in a mergable state, due to the last commit. I wasn't able to build without this change, so I was wondering if anybody else has feedback on how I can fix this.

Andrei

### CODE REVIEW

**Comment by matzipan** [comment]
@antoyo was suggesting on matrix that the solution might be renaming crates, similar to the way it's done in webkit2gtk-sys/Gir.toml.

But with this diff:
```
$ git diff Gir.toml
diff --git a/Gir.toml b/Gir.toml
index 8f04cd1..d8d9232 100644
--- a/Gir.toml
+++ b/Gir.toml
@@ -12,10 +12,12 @@ single_version_file = true
 
 external_libraries = [
     "Gio",
-    "Gtk",
-    "JavaScriptCore",
+    "Gtk"
 ]
 
+[external_libraries]
+java_script_core = "JavaScriptCore"
+
 generate = [
     "WebKit2.ApplicationInfo",
     "WebKit2.AuthenticationScheme",
```

I have also tried with `javascriptcore = "JavaScriptCore"`

I get the following error:
```
$ make girjava_script_core = "JavaScriptCore"
gir/target/bin/gir -c Gir.toml
For external library "generate" namespace must be string
Makefile:28: recipe for target 'src/auto/mod.rs' failed
make: *** [src/auto/mod.rs] Error 1
```

Which is this error line here: https://github.com/gtk-rs/gir/blob/master/src/config/external_libraries.rs#L36

But at the end of the day, I don't understand why this is error happens, especially since the gir test in the same file looks similar:
```
[options]
external_libraries = [
   "GLib",
   "Gdk",
   "GdkPixbuf",
]
[external_libraries]
coollib="CoolLib"
other-lib="OtherLib"
```

**Comment by matzipan** [comment]
Ok, so it seems that by adding `[external_libraries]` I was defining a new config section and the generate property below was not liking it. I put the snippet at the bottom and gir doesn't complain anymore. But it still doesn't generate the right imports.

**Comment by matzipan** [comment]
Ok! fixed in `Cargo.toml` with `[dependencies.java_script_core]`

**Comment by matzipan** [comment]
I rebased this on #83 on @bilelmoussaoui's advice.  Let's see if the CI will be green now.

**Comment by bilelmoussaoui** [comment]
You still need to update the manual code in src/ to use rust 2018 way of importing modules (prefixing stuff with `crate::`)

**Comment by matzipan** [comment]
Yeah, the problem is locally I was testing with `cargo build`, whereas the CI tested with `cargo build --features=v2_28`. So I wasn't sure what the error was.

**Comment by matzipan** [comment]
Eyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy. It's green!

**Comment by antoyo** [comment]
Thank you so much for your work.

**Pull request merged**
