### PR TITLE
Point the git deps to the gtk-rs monorepo

### PR DESCRIPTION
**Pull request by matzipan**

### CODE REVIEW

**Comment by matzipan** [comment]
I'm not sure why the CI is failing, since I haven't touched the Gir file: `Invalid indent in `./webkit2gtk-sys/Gir.toml:11`: it must be a multiple of 4!` :(

**Comment by matzipan** [comment]
The other failures seem to be because of javascript-core issues for which I will push another PR in a moment.

**Comment by bilelmoussaoui** [comment]
This need to be merged with #82 for it to work as the code generated by gir changed and it can't work like this

**Comment by matzipan** [comment]
Ok, I rebased #82 on this one so I'm closing it here.

**Pull request closed without merging**
