### PR TITLE
Regen crate

### PR DESCRIPTION
**Pull request by jangernert**
- update gir files
- regen both crates
- update dependencies
- bump versions

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Do you mind sending a patch to update the crate branch of https://github.com/gtk-rs/webkit2gtk-webextension-rs as well?

**Comment by jangernert** [comment]
https://github.com/gtk-rs/webkit2gtk-webextension-rs/pull/51

**Comment by jangernert** [comment]
@antoyo needless to say: I hope you find the time to push this new version to crates.io soon

**Comment by antoyo** [comment]
@jangernert: Done.

**Pull request merged**
