### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by gigitux**
I've cherry-picked all commits from the last regen that was done in master

### CODE REVIEW

**Comment by antoyo** [comment]
The CI is failing. It seems like the `build.rs` file was not generated correctly. Usually, I don't do cherry-picks, I just do a regen for that branch.

**Comment by gigitux** [comment]
Thanks for the feedback! Hopefully the build now goes correctly!

**Comment by antoyo** [comment]
Sorry but I merged with missing changes.
This is still missing the features like in [`master`](https://github.com/gtk-rs/webkit2gtk-rs/blob/master/Cargo.toml#L32-L38).
Can you please create a new PR?

**Comment by gigitux** [comment]
Yes you are right! I noticed it too! 

Within half an hour I update the PR!

**Pull request merged**
