### PR TITLE
Remove callback guard

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/glib/pull/250

cc @GuillaumeGomez, @antoyo

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
This one is up to @antoyo. :)

(But 👍 for me)

**Comment by antoyo** [comment]
This deprecates stuff like [this](https://github.com/gtk-rs/webkit2gtk-rs/blob/master/src/web_view.rs#L88-L90), but I can merge as is.

**Comment by EPashkin** [comment]
Normal mode need single_version_file too, missed that

**Comment by antoyo** [comment]
@EPashkin Here's the newly automatically generated [`run_javascript` function](https://github.com/gtk-rs/webkit2gtk-rs/pull/38/files#diff-28293a78c7b94afe2094f183359f8a7eR766).

**Comment by EPashkin** [comment]
I will remove duplicate

**Comment by EPashkin** [comment]
Updated with temporary version

**Comment by antoyo** [comment]
Looks good.
Please tell me when I can merge.

**Comment by EPashkin** [comment]
I thought that some warnings left.
IMHO all done

**Pull request merged**
