### PR TITLE
Update to the latest gir/gir-files

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This should allow to have a release of webkit2gtk-rs on time :)

### CODE REVIEW

**Comment by antoyo** [comment]
Thanks for the PR.
By the way, it's not the master branch which is released: it's the crate branch.
So, I would appreciate if you do a PR against the crate branch.

**Comment by bilelmoussaoui** [comment]
Sure, I will do one once the CI passes

**Comment by EPashkin** [comment]
@antoyo Better not do direct PRs to crate branch, only merging master to it,
or you use different workflow ?

**Comment by antoyo** [comment]
@EPashkin: I used always did another regen for the crate branch. Merging master never worked in my case. What is the workflow used by the other gtk-rs crates?

**Comment by EPashkin** [comment]
We add user's PR to master branch only, 
then merge master to crate periodically with updating versions,
@GuillaumeGomez write script in https://github.com/gtk-rs/release/
not sure what it works for you

**Comment by GuillaumeGomez** [comment]
The repositories maintained by @antoyo are a bit on their own. I don't interfere with their release system. :)

**Comment by bilelmoussaoui** [comment]
@antoyo do you mind re-triggering the CI? :)

**Comment by antoyo** [comment]
@bilelmoussaoui Done.

**Comment by EPashkin** [comment]
@bilelmoussaoui Manual changes in generated code don't pass CI's regen_check

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui Manual changes in generated code don't pass CI's regen_check

I guess I should disable generarting that method for now; it wasn't being generated before neither

**Comment by antoyo** [comment]
@bilelmoussaoui Is that ready for review?

**Comment by bilelmoussaoui** [comment]
Yes, should be ready

**Comment by bilelmoussaoui** [comment]
@antoyo Thanks, do you mind reviewing this one https://github.com/gtk-rs/webkit2gtk-webextension-rs/pull/50 as well? :) I will send an update to the crate branch

**Pull request merged**
