### PR TITLE
[WIP] Regen crate branch

### LINKED ISSUE #63: New Release
I'll open this for visibility. Even with #58 closed there still needs to be a release to use `webkit2gtk-rs` together with the rest of the latest `gtk-rs` stack.

### PR DESCRIPTION
**Pull request by jangernert**
First time committing to `gtk-rs` bindings. So please tell me if I missed something.

edit:
Fixes #63

### CODE REVIEW

**Comment by jangernert** [comment]
Commit log should be clean now. 
@antoyo  Do you want the commits structured differently? Squash everything? Keep the commit touching `/auto/` separate?

Any objections to updating `bitflags` in the `webkit2gtk-sys` crate? `webkit2gtk` is already using the most recent version. And having 2 different version of the same dependency (if not absolutely needed for something) always bugs me.

**Comment by antoyo** [comment]
You can update `bitflags`.
Everything else is fine.
Thanks.

**Comment by jangernert** [comment]
I think we're good to go then.

**Comment by antoyo** [comment]
Can you update the version of the `-sys` crate?
After that, I'll merge and deploy.

**Comment by jangernert** [comment]
@antoyo done

**Comment by jangernert** [comment]
@antoyo done

**Comment by antoyo** [comment]
The crates are deployed.
Thanks for your contribution.

**Comment by jangernert** [comment]
Thank you for pointing me in the right directions.
For the next `gtk-rs` release I'll just update `webkit2gtk` instead of annoying people with issue reports :D

**Pull request merged**
