### PR TITLE
Regenrate the bindings with the latest gtk-rs stack

### LINKED ISSUE #58: Issues when used with new gtk-rs stack
Updated to the new gtk-rs stack
```
cairo-rs = "0.8"
pango = "0.8"
glib = { version = "0.9" }
gdk-pixbuf = { version = "0.8", features = ["v2_36"] }
gtk = { version = "0.8", features = ["v3_24"] }
gio = { version = "0.8", features = ["v2_58"] }
gdk = { version = "0.12", features = ["v3_24"] }
webkit2gtk = { version = "0.8", features = ["v2_16"] }
```

But I'm getting lots of 
```
the trait `glib::object::IsA<gtk::auto::widget::Widget>` is not implemented for `webkit2gtk::auto::web_view::WebView`
```

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Depends on https://github.com/gtk-rs/gir/issues/872 being fixed
Closes #55 
Fixes #58

### CODE REVIEW

**Comment by antoyo** [comment]
The CI failed. Do you know why?

**Comment by bilelmoussaoui** [comment]
> The CI failed. Do you know why?

Should be fine now. Forgot to update some files, it passes the build & tests locally.

**Comment by bilelmoussaoui** [comment]
Should be ready now

**Comment by EPashkin** [comment]
IMHO missed gir submodule update and sys regen

**Comment by bilelmoussaoui** [comment]
> IMHO missed gir submodule update and sys regen
> 
> Edit: was wrong, only sys regen is not done

Somehow missed the sys one. Fixed

**Comment by EPashkin** [comment]
@antoyo @GuillaumeGomez CI passed

**Comment by bilelmoussaoui** [comment]
@antoyo thanks for the quick merge, is a new release planned soon?

**Comment by antoyo** [comment]
@bilelmoussaoui: The release is done with the `crate` branch.
I might do the regen of this branch in 1-2 weeks, but if you want it earlier, I'd appreciate a PR with the regen in the `crate` branch.
Thank you.

**Comment by EPashkin** [comment]
@antoyo, @bilelmoussaoui  Please do not forget that https://github.com/gtk-rs/webkit2gtk-webextension-rs also needs to be updated

**Comment by EPashkin** [comment]
Hm, only changes is `use` order, I added https://github.com/gtk-rs/webkit2gtk-webextension-rs/pull/47

**Pull request merged**
